# Generated by Django 4.2.7 on 2023-11-11 14:35

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body_1',
            field=wagtail.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_2',
            field=wagtail.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description_project_1',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description_project_2',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description_project_3',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='logo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='logo_image_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_image_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_image_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_project_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_project_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_project_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='open_fri',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='open_mon',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='open_sat',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='open_sun',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='open_thu',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='open_tue',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='open_wed',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='street',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tel_home',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tel_mobi',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_1',
            field=models.CharField(max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_2',
            field=models.CharField(max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_project_1',
            field=models.CharField(max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_project_2',
            field=models.CharField(max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_project_3',
            field=models.CharField(max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='zip_city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
