# Generated by Django 4.2.7 on 2023-11-22 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0003_homepage_body_1_homepage_body_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('member_name_surname', models.CharField(max_length=81, null=True)),
                ('member_role', models.CharField(max_length=40, null=True)),
                ('member_description', models.CharField(max_length=255, null=True)),
                ('member_socials_fb', models.CharField(max_length=155, null=True)),
                ('member_socials_x', models.CharField(max_length=155, null=True)),
                ('member_socials_instagram', models.CharField(max_length=155, null=True)),
                ('member_socials_linkedin', models.CharField(max_length=155, null=True)),
                ('member_socials_yt', models.CharField(max_length=155, null=True)),
                ('member_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
