# Generated by Django 4.2.7 on 2023-11-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_teammember_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='member_socials_fb',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='member_socials_instagram',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='member_socials_linkedin',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='member_socials_x',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='member_socials_yt',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
