# Generated by Django 4.2.7 on 2023-11-23 17:36

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_servicespage_services_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicespage',
            name='services_body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('subheading', wagtail.blocks.CharBlock(form_classname='sub title')), ('paragraph_style_1', wagtail.blocks.RichTextBlock()), ('paragraph_style_2', wagtail.blocks.RichTextBlock()), ('paragraph_style_3', wagtail.blocks.RichTextBlock()), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('alert', wagtail.blocks.CharBlock(form_classname='alert'))], use_json_field=True),
        ),
    ]
