# Generated by Django 4.2.7 on 2023-11-23 18:33

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_servicespage_services_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicespage',
            name='services_body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title', label='Główny nagłówek')), ('subheading', wagtail.blocks.CharBlock(form_classname='sub title', label='Podnagłówek - mniejsze pogrubienie, mniejsza czcionka')), ('paragraph_style_1', wagtail.blocks.RichTextBlock(label='Czcionka: 20px, wyśrodkowany, kolor brąz')), ('paragraph_style_2', wagtail.blocks.RichTextBlock(label='Czcionka: 24px, lekko pogrubiony,            wyśrodkowany, kolor szary')), ('paragraph_style_3', wagtail.blocks.RichTextBlock(label='Czcionka: 24px, kolor brąz')), ('paragraph', wagtail.blocks.RichTextBlock(label='Defaultowe style')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('image_small', wagtail.images.blocks.ImageChooserBlock()), ('alert', wagtail.blocks.CharBlock(form_classname='alert'))], use_json_field=True),
        ),
    ]
